export const SSM_KEYS = {
  VPC_ID: '/idp-code/vpc/id',
  AURORA_CLUSTER_ENDPOINT: '/idp-code/aurora/cluster-endpoint',
  AURORA_CLUSTER_PORT: '/idp-code/aurora/cluster-port',
  AURORA_SECRET_ARN: '/idp-code/aurora/secret-arn',
  RDS_PROXY_ENDPOINT: '/idp-code/aurora/proxy-endpoint',
  RDS_PROXY_SG_ID: '/idp-code/aurora/proxy-sg-id',
  INGEST_QUEUE_URL: '/idp-code/ingest/queue-url',
  COGNITO_DOMAIN: '/idp-code/cognito/domain',
  COGNITO_APP_CLIENT_ID: '/idp-code/cognito/app-client-id',
  COGNITO_IDENTITY_POOL_ID: '/idp-code/cognito/identity-pool-id',
  COGNITO_USER_POOL_ID: '/idp-code/cognito/user-pool-id',
  API_FUNCTION_ARN: '/idp-code/api/function-arn',
  MIGRATION_FUNCTION_ARN: '/idp-code/migration/function-arn',
  FRONTEND_DISTRIBUTION_ID: '/idp-code/frontend/distribution-id',
  FRONTEND_DISTRIBUTION_DOMAIN: '/idp-code/frontend/distribution-domain',
  COGNITO_WEB_CLIENT_ID: '/idp-code/cognito/web-client-id',
  COGNITO_WEB_IDENTITY_POOL_ID: '/idp-code/cognito/web-identity-pool-id',
  AGENT_RUNTIME_ARN: '/idp-code/agent/runtime-arn',
} as const;
