[env]
NX_STREAM_OUTPUT = "true"
AWS_REGION = "ap-northeast-2"

[tasks.deploy]
description = "Deploy a specific CDK stack (fzf)"
run = """
stack=$(echo "IDP-CODE-NETWORK\nIDP-CODE-STORAGE\nIDP-CODE-APPLICATION\nIDP-CODE-AUTH" | fzf --prompt="Select stack: ")
pnpm nx run @idp-code/infra:deploy $stack --output-style=stream
"""

[tasks.checkov]
description = "Run checkov on CDK synthesized CloudFormation templates"
run = "pnpm nx run @idp-code/infra:synth && checkov --skip-download -d dist/packages/infra/cdk.out"
